apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: in-cluster
  name: in-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: in-cluster
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: in-cluster
    spec:
      containers:
      - image: evanraisul/in-cluster:latest
        name: in-cluster
        resources: {}
status: {}
